import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Copy, Check, Download, ShieldCheck, AlertTriangle } from 'lucide-react';
import { useForensicsContext } from '../context/ForensicsContext';
import { GlassCard } from '../components/common/GlassCard';
import { Button } from '../components/common/Button';
import { EmptyState } from '../components/common/EmptyState';

export const Reports: React.FC = () => {
  const navigate = useNavigate();
  const { currentRun } = useForensicsContext();
  const [copied, setCopied] = useState(false);

  if (!currentRun) {
    return (
      <EmptyState
        title="NO INCIDENT REPORT GENERATED"
        description="Run a diagnostic workflow to generate a formal, exportable multi-agent failure forensics incident report."
        actionLabel="Go to Investigation Workspace"
        onAction={() => navigate('/investigation')}
        icon={<FileText className="w-8 h-8" />}
      />
    );
  }

  const { id, task, scenario_label, timestamp, trace, diagnosis, replay } = currentRun;

  const reportMarkdown = `# FAULTLINE INCIDENT FORENSIC REPORT
Case ID: ${id}
Timestamp: ${timestamp}
Scenario: ${scenario_label}
Task Prompt: ${task}

## 1. EXECUTIVE SUMMARY
Verdict: ${diagnosis.unknown ? 'INSUFFICIENT EVIDENCE' : diagnosis.has_failure ? 'ROOT CAUSE IDENTIFIED' : 'PASSED CLEAN'}
Primary Responsible Agent: ${diagnosis.root_cause_agent || 'None'} (Step ${diagnosis.root_cause_step || '—'})
Failure Classification: ${diagnosis.root_cause_error_type}

## 2. DETERMINISTIC EVIDENCE
- Expected Output: ${diagnosis.root_cause_expected ?? 'N/A'}
- Actual Received: ${diagnosis.root_cause_actual ?? 'N/A'}
- Validation Reason: ${diagnosis.root_cause_reason || 'Validation passed'}

## 3. BLAST RADIUS & PROPAGATION
- Affected Downstream Agents: ${diagnosis.downstream_agents?.length ? diagnosis.downstream_agents.join(', ') : 'None'}
- Total Steps Evaluated: ${trace.length}

## 4. COUNTERFACTUAL VERIFICATION
- Replay Executed: ${replay ? 'Yes' : 'No'}
- Recovery Verified: ${replay?.recovered ? 'YES (All steps passed)' : 'NO / Not Executed'}

## 5. RECOMMENDED REMEDIATION
${diagnosis.remediation || 'No remediation required.'}

Generated by FAULTLINE AI Observability & Forensics Console
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FAULTLINE-REPORT-${id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fadeIn pb-12 max-w-5xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight font-sans flex items-center gap-2">
            <FileText className="w-5 h-5 text-violet-600" />
            INCIDENT FORENSIC REPORT
          </h2>
          <p className="text-xs text-slate-500 font-mono mt-0.5">
            Formal post-incident failure attribution & causal verification documentation
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            size="sm"
            icon={copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            onClick={handleCopy}
          >
            {copied ? 'Copied Markdown' : 'Copy Report'}
          </Button>
          <Button
            variant="primary"
            size="sm"
            icon={<Download className="w-3.5 h-3.5" />}
            onClick={handleDownload}
          >
            Export Markdown
          </Button>
        </div>
      </div>

      {/* Formal Report Layout */}
      <GlassCard glow="violet" className="p-8 space-y-6 font-mono text-xs leading-relaxed bg-white/90 border-slate-200/80">
        {/* Report Header */}
        <div className="border-b border-slate-200/80 pb-5 flex items-center justify-between">
          <div>
            <span className="text-[10px] text-violet-700 uppercase tracking-widest font-bold">
              FAULTLINE FORENSIC AUDIT
            </span>
            <h3 className="text-lg font-bold text-slate-900 mt-1 font-sans">
              Case File: {id}
            </h3>
          </div>
          <span className="text-slate-500 text-[11px]">
            {new Date(timestamp).toLocaleString()}
          </span>
        </div>

        {/* Section 1: Executive Summary */}
        <div>
          <h4 className="text-xs font-bold text-violet-700 uppercase tracking-wider mb-2">
            1. Executive Forensic Summary
          </h4>
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 shadow-sm grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <span className="text-slate-500 block mb-1 font-semibold">Attribution Finding:</span>
              <span className={`text-sm font-bold ${diagnosis.has_failure ? 'text-rose-700' : 'text-emerald-700'}`}>
                {diagnosis.unknown
                  ? 'INSUFFICIENT EVIDENCE'
                  : diagnosis.has_failure
                  ? `${diagnosis.root_cause_agent} (Step ${diagnosis.root_cause_step})`
                  : 'VALIDATED CLEAN'}
              </span>
            </div>
            <div>
              <span className="text-slate-500 block mb-1 font-semibold">Failure Taxonomy:</span>
              <span className="text-slate-900 font-bold uppercase">
                {diagnosis.root_cause_error_type}
              </span>
            </div>
          </div>
        </div>

        {/* Section 2: Deterministic Evidence */}
        <div>
          <h4 className="text-xs font-bold text-violet-700 uppercase tracking-wider mb-2">
            2. Ground-Truth Evidence Comparison
          </h4>
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 shadow-sm space-y-3">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <span className="text-slate-500 block mb-1 font-semibold">Expected Output:</span>
                <span className="text-emerald-700 font-bold text-sm">
                  {diagnosis.root_cause_expected ?? '—'}
                </span>
              </div>
              <div>
                <span className="text-slate-500 block mb-1 font-semibold">Actual Received:</span>
                <span className="text-rose-700 font-bold text-sm">
                  {diagnosis.root_cause_actual ?? '—'}
                </span>
              </div>
            </div>
            <div className="pt-2 border-t border-slate-200">
              <span className="text-slate-500 block mb-1 font-semibold">Validation Reason:</span>
              <span className="text-slate-700">
                {diagnosis.root_cause_reason || 'Pipeline executed cleanly.'}
              </span>
            </div>
          </div>
        </div>

        {/* Section 3: Blast Radius */}
        <div>
          <h4 className="text-xs font-bold text-violet-700 uppercase tracking-wider mb-2">
            3. Blast Radius & Downstream Propagation
          </h4>
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 shadow-sm">
            <span className="text-slate-500 block mb-1 font-semibold">Impacted Downstream Agents:</span>
            <span className="text-slate-900 font-bold">
              {diagnosis.downstream_agents?.length ? diagnosis.downstream_agents.join(', ') : 'None (No cascade)'}
            </span>
          </div>
        </div>

        {/* Section 4: Counterfactual Verification */}
        <div>
          <h4 className="text-xs font-bold text-violet-700 uppercase tracking-wider mb-2">
            4. Counterfactual Verification
          </h4>
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 shadow-sm">
            <span className="text-slate-500 block mb-1 font-semibold">Empirical Recovery Proof:</span>
            <span className={`font-bold ${replay?.recovered ? 'text-emerald-700' : 'text-slate-500'}`}>
              {replay?.recovered
                ? '✅ VERIFIED: Controlled re-run succeeded after removing injected fault.'
                : 'Counterfactual replay not yet executed or failed.'}
            </span>
          </div>
        </div>

        {/* Section 5: Remediation */}
        <div>
          <h4 className="text-xs font-bold text-violet-700 uppercase tracking-wider mb-2">
            5. Recommended Corrective Action
          </h4>
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 shadow-sm text-slate-700">
            {diagnosis.remediation || 'No corrective action required.'}
          </div>
        </div>
      </GlassCard>
    </div>
  );
};
